export const SystemReviewOptions = {
    piel: 'Piel',
    cabeza: 'Cabeza',
    Otorrinolaringologia: 'Otorrinolaringologia',
    Ojos: 'Ojos',
    Cuello: 'Cuello',
    Torax: 'Torax',
    Mamas: 'Mamas',
    Cardiovascular: 'Cardiovascular',
    Abdomen: 'Abdomen',
    Genital: 'Genital',
    Extremidades: 'Extremidades',
    Neurologico: 'Neurologico',
    NiegaRevisionPorSistema: 'NiegaRevisionPorSistema',
};

export const PersonalHistoryOptions = {
    perinatales: 'Perinatales',
    desarrolloPsicomotor: 'Desarrollo psicomotor',
    patalogicos: 'Patalogicos',
    alergico: 'Alergico',
    traumaticos: 'Traumaticos',
    venereas: 'Venereas',
    ginecoObstetricos: 'Gineco-Obstetricos',
    fechaDeUltimaRegla: 'Fecha de ultima regla',
    fechaDeUltimoParto: 'Fecha de ultimo parto',
    fechaDeUltimaCitologia: 'Fecha de ultima citologia',
    fechaDeUltimaMamografia: 'Fecha de Ultima mamografia',
    hospitalizaciones: 'Hospitalizaciones',
    farmacologicos: 'Farmacologicos',
    cocinoConLena: 'Cocino con leña',
    tabaco: 'Tabaco',
    cancer: 'Cancer',
    niegaAntecedentePersonales: 'Niega antecedentes personales',
};
